all:
  children:
    swarm:
      children:
        managers:
          hosts:
            alpha:
              ansible_host: 10.10.10.100
              ansible_user: ray
            beta.local:
              ansible_host: 10.10.10.101
              ansible_user: ray
        workers:
          hosts:
            gamma.local:
              ansible_host: 10.10.10.102
              ansible_user: ray
            delta.local:
              ansible_host: 10.10.10.103
              ansible_user: ray
